# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7ad83e5687ffb5f533bdab4b5e79d03f2e02fe21b572d17683e024ca54b5fe824ce708baff5a14aa79e8c0d3acdfeddad717d84e66bbdd54e700086c7168142

test:
  secret_key_base: 65fc14f37d3a79b5a8a7aa4dada1fa20d7a79d974c96ff12f985337caf283f7de80a4ef0b98e8e94306bca0b6c6578c312ae01f08a4c4a1461b32bcdf5fcbdfb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
